baseURL = 'https://blog.dsnb.cc/'
languageCode = 'zh-cn'
title = '东少博客'

[params]
title = "DongShaoNB / 东少"
author = "DongShaoNB"
description = "你好，我是东少，很高兴认识你"
profilePicture = "images/profile.png"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false